project_name: zusatzschaltflaechen-proffix-go
builds:
  - main: google-maps/main.go
    binary: google-maps
    goos:
      - windows
    goarch:
      - amd64
  - main: send-email/main.go
    binary: send-email
    goos:
      - windows
    goarch:
      - amd64
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    windows: Windows
    amd64: 64-bit
    darwin: macOS
  files:
    - send-email/config.json.ex
  format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: pitw
    name: zusatzschaltflaechen-go-proffix
  draft: false
  prerelease: false
  name_template: "{{.ProjectName}}-v{{.Version}}"